(() => {
  'use strict';
  const PROMOTIONS_DISABLED=true;
  if(PROMOTIONS_DISABLED)return;
  if (document.querySelector('#promoScrim')) return;
  const lang=document.documentElement.lang==='es'?'es':'en';
  const copy=lang==='es'?{badge:'Oferta especial',close:'Cerrar',code:'Código',cta:'Reservar una consulta',dismiss:'No, gracias. Solo estoy mirando.',sample:'Vista previa de muestra; no hay ningún descuento activo.'}:{badge:'A little something',close:'Close',code:'Code',cta:'Book a consultation',dismiss:'No thanks, just browsing.',sample:'Sample preview only. No discount is live or being advertised.'};
  const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('offer-popup.css',document.currentScript.src).href;document.head.append(style);
  const scrim=document.createElement('div');scrim.className='promo-scrim';scrim.id='promoScrim';scrim.innerHTML='<section class="promo-card" role="dialog" aria-modal="true"><button class="promo-close" type="button" aria-label="'+copy.close+'">×</button><div class="promo-image" hidden></div><div class="promo-top"><span class="promo-badge"></span><h2 class="promo-head"></h2><p class="promo-sub"></p></div><div class="promo-body"><ul class="promo-bullets" hidden></ul><strong class="promo-price" hidden></strong><div class="promo-code" hidden><span class="promo-code-label"></span><strong class="promo-code-val"></strong></div><a class="promo-cta" target="_blank" rel="noopener"></a><p class="promo-fine"></p><a class="promo-dismiss" href="#"></a></div></section>';
  document.body.append(scrim);
  const dismiss=()=>{scrim.classList.remove('open');document.body.classList.remove('locked');try{sessionStorage.setItem('preciseOfferSeen','1');}catch{}};
  scrim.querySelector('.promo-close').addEventListener('click',dismiss);scrim.querySelector('.promo-dismiss').addEventListener('click',e=>{e.preventDefault();dismiss();});scrim.addEventListener('click',e=>{if(e.target===scrim)dismiss();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&scrim.classList.contains('open'))dismiss();});
  const preview=new URLSearchParams(location.search).has('preview'),local=['127.0.0.1','localhost'].includes(location.hostname),endpoint=local?'http://127.0.0.1:8818/api/offer':'https://precise-laser-crm.pages.dev/api/offer';
  try{if(!preview&&sessionStorage.getItem('preciseOfferSeen'))return;}catch{}
  const show=offer=>{if(!offer.active)return;const card=scrim.querySelector('.promo-card');card.classList.toggle('is-background',offer.layout==='background');card.classList.toggle('has-image',!!offer.imageUrl);card.classList.toggle('has-brand',offer.showHeader!==false);card.style.background=offer.layout==='background'?(offer.imageUrl?'#16302e':'linear-gradient(140deg,#1e8a85,#14615d)'):'';card.style.setProperty('--offer-ink',/^#[\da-f]{6}$/i.test(offer.textColor||'')?offer.textColor:'#ffffff');card.setAttribute('aria-label',offer.headline||copy.badge);scrim.querySelector('.promo-badge').textContent=offer.badge||copy.badge;scrim.querySelector('.promo-head').textContent=offer.headline;scrim.querySelector('.promo-sub').textContent=offer.subline;scrim.querySelector('.promo-cta').textContent=offer.cta||copy.cta;scrim.querySelector('.promo-cta').href=offer.bookingUrl||'https://book.squareup.com/appointments/gs1i408ex6v4ly/location/LQD6Q4Z7MZVFG/services';scrim.querySelector('.promo-fine').textContent=offer.fine||'';scrim.querySelector('.promo-code-label').textContent=copy.code;scrim.querySelector('.promo-code-val').textContent=offer.code||'';scrim.querySelector('.promo-code').hidden=!offer.code;const image=scrim.querySelector('.promo-image');image.hidden=!offer.imageUrl;if(offer.imageUrl)image.style.backgroundImage=`url("${new URL(offer.imageUrl,endpoint)}")`;const bullets=scrim.querySelector('.promo-bullets');bullets.replaceChildren(...(offer.bullets||[]).slice(0,5).map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));bullets.hidden=!bullets.children.length;const price=scrim.querySelector('.promo-price');price.textContent=offer.price||'';price.hidden=!offer.price;setTimeout(()=>{scrim.classList.add('open');document.body.classList.add('locked');},preview?0:Math.min(60,Number(offer.delaySeconds)||0)*1000);};
  const demo={active:true,badge:lang==='es'?'MUESTRA DE VISTA PREVIA':'PREVIEW OFFER',headline:lang==='es'?'Un detalle especial para tu próxima visita':'A little extra for your next visit',subline:lang==='es'?'Una oferta flexible para servicios de láser, cuidado de la piel o bienestar.':'A flexible offer card for laser, skincare, or wellness services.',cta:copy.cta,bookingUrl:'https://book.squareup.com/appointments/gs1i408ex6v4ly/location/LQD6Q4Z7MZVFG/services',fine:copy.sample,delaySeconds:0};
  fetch(endpoint+'?lang='+lang,{cache:'no-store'}).then(r=>r.ok?r.json():{active:false}).then(offer=>{if(!offer.active&&preview&&local)offer=demo;show(offer);}).catch(()=>{if(preview&&local)show(demo);});
})();
