name = "web-precise-laser"
compatibility_date = "2026-10-08"
pages_build_output_dir = "public"

[[env.production.d1_databases]]
binding = "DB"
database_name = "precise-laser-crm"
database_id = "59423115-7227-44f2-9795-ea6fb38f8f73"
